### ISSUE TITLE
Error running test data set (small.pq, small.config)

### ISSUE THREAD

**Issue by apdavid** [salzmanlab/SpliZ#1]
I tried running the test data set, following the directsion in the README and came across this error, unclear where `path domain` is missing, is it in the `*.config` file?

```
$ nextflow run salzmanlab/spliz -r main -latest -c small.config                                                                  
N E X T F L O W  ~  version 21.04.0
Pulling salzmanlab/spliz ...
 Already-up-to-date
Launching `salzmanlab/spliz` [wise_cuvier] - revision: 6c708f518b [main]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/spliz v1.0dev
------------------------------------------------------


WARN: Found unexpected parameters:
* --outdir: ./results/test
* --numGenes: null
* --domain: null
- Ignore this warning: params.schema_ignore_params = "outdir,numGenes,domain" 

Core Nextflow options
  revision              : main
  runName               : wise_cuvier
  container             : kaitlinchaung/spliz:dev
  launchDir             : /***
  workDir               : /***
  projectDir            : /***
  userName              : ***
  profile               : standard
  configFiles           : /***/.nextflow/assets/salzmanlab/spliz/nextflow.config, /***/small.config


Input/output options
  dataname              : test
  input_file            : small.pq
  SICILIAN              : true
  pin_S                 : 0.1
  pin_z                 : 0.0
  bounds                : 5
  light                 : false
  svd_type              : normdonor
  grouping_level_1      : tissue
  grouping_level_2      : compartment
  n_perms               : 100
  libraryType           : 10X
  run_analysis          : true

Max job request options
  max_memory            : 800 GB
  max_time              : 10d

Other parameters
  max_multiqc_email_size: 25 MB

------------------------------------------------------
 Only displaying parameters that differ from defaults.
------------------------------------------------------
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:SPLIZ:CALC_SPLIZVD         -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:PVAL_PERMUTATIONS -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:FIND_SPLIZ_SITES  -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:SUMMARIZE_RESULTS -


A process input channel evaluates to null -- Invalid declaration `path domain`

 -- Check script '.nextflow/assets/salzmanlab/spliz/./workflows/./../subworkflows/local/analysis.nf' at line: 49 or see '.nextflow.log' file for more details
```

And the `.nextflow.log` file shows this:

```
(base) [adavid@dev3 ~]$ cat .nextflow.log
Sep-11 21:18:17.084 [main] DEBUG nextflow.cli.Launcher - Setting http proxy: [prox1, 3128]
Sep-11 21:18:17.186 [main] DEBUG nextflow.cli.Launcher - Setting https proxy: [prox1, 3128]
Sep-11 21:18:17.187 [main] DEBUG nextflow.cli.Launcher - $> nextflow run salzmanlab/spliz -r main -latest -c small.config
Sep-11 21:18:17.321 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.0
Sep-11 21:18:19.037 [main] DEBUG nextflow.scm.AssetManager - Git config: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/.git/config; branch: master; remote: origin; url: https://github.com/salzmanlab/SpliZ.git
Sep-11 21:18:19.076 [main] DEBUG nextflow.scm.AssetManager - Git config: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/.git/config; branch: master; remote: origin; url: https://github.com/salzmanlab/SpliZ.git
Sep-11 21:18:19.077 [main] INFO  nextflow.cli.CmdRun - Pulling salzmanlab/spliz ...
Sep-11 21:18:19.078 [main] DEBUG nextflow.scm.AssetManager - Pull pipeline salzmanlab/spliz  -- Using local path: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz
Sep-11 21:18:21.157 [main] INFO  nextflow.cli.CmdRun -  Already-up-to-date
Sep-11 21:18:21.299 [main] INFO  nextflow.cli.CmdRun - Launching `salzmanlab/spliz` [wise_cuvier] - revision: 6c708f518b [main]
Sep-11 21:18:21.316 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/nextflow.config
Sep-11 21:18:21.319 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /wynton/home/tjan/adavid/small.config
Sep-11 21:18:21.320 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/nextflow.config
Sep-11 21:18:21.320 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /wynton/home/tjan/adavid/small.config
Sep-11 21:18:21.333 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Sep-11 21:18:21.802 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-11 21:18:21.811 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-11 21:18:21.820 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Sep-11 21:18:22.149 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Sep-11 21:18:22.292 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/wynton/home/tjan/adavid/.nextflow/plugins
Sep-11 21:18:22.296 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Sep-11 21:18:22.297 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins local root: .nextflow/plr/empty
Sep-11 21:18:22.303 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-11 21:18:22.303 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-11 21:18:22.306 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Sep-11 21:18:22.320 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Sep-11 21:18:22.432 [main] DEBUG nextflow.Session - Session uuid: 34d210c5-9c89-4ab7-8dc7-56a8b0a80ef8
Sep-11 21:18:22.432 [main] DEBUG nextflow.Session - Run name: wise_cuvier
Sep-11 21:18:22.433 [main] DEBUG nextflow.Session - Executor pool size: 32
Sep-11 21:18:22.558 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.04.0 build 5552
  Created: 02-05-2021 16:22 UTC (09:22 PDT)
  System: Linux 3.10.0-1160.36.2.el7.x86_64
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 20412@dev3.wynton.ucsf.edu [172.26.44.133]
  CPUs: 32 - Mem: 503.8 GB (417.3 GB) - Swap: 4 GB (1.3 GB)
Sep-11 21:18:22.598 [main] DEBUG nextflow.Session - Work-dir: /wynton/home/tjan/adavid/work [fhgfs]
Sep-11 21:18:22.649 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Sep-11 21:18:22.667 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Sep-11 21:18:23.387 [main] DEBUG nextflow.Session - Session start invoked
Sep-11 21:18:23.408 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /wynton/home/tjan/adavid/results/pipeline_info/execution_trace_2021-09-11_21-18-22.txt
Sep-11 21:18:23.446 [main] DEBUG nextflow.Session - Using default localLib path: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/lib
Sep-11 21:18:23.455 [main] DEBUG nextflow.Session - Adding to the classpath library: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/lib
Sep-11 21:18:23.456 [main] DEBUG nextflow.Session - Adding to the classpath library: /wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/lib/nfcore_external_java_deps.jar
Sep-11 21:18:25.347 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Sep-11 21:18:25.385 [main] INFO  nextflow.Nextflow - 

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/spliz v1.0dev
------------------------------------------------------

Sep-11 21:18:25.737 [main] WARN  nextflow.Nextflow - Found unexpected parameters:
* --outdir: ./results/test
* --numGenes: null
* --domain: null
Sep-11 21:18:25.739 [main] INFO  nextflow.Nextflow - - Ignore this warning: params.schema_ignore_params = "outdir,numGenes,domain" 
Sep-11 21:18:25.824 [main] INFO  nextflow.Nextflow - Core Nextflow options
  revision              : main
  runName               : wise_cuvier
  container             : kaitlinchaung/spliz:dev
  launchDir             : /***
  workDir               : /***
  projectDir            : /***
  userName              : ***
  profile               : standard
  configFiles           : /***/.nextflow/assets/salzmanlab/spliz/nextflow.config, /***/small.config

Input/output options
  dataname              : test
  input_file            : small.pq
  SICILIAN              : true
  pin_S                 : 0.1
  pin_z                 : 0.0
  bounds                : 5
  light                 : false
  svd_type              : normdonor
  grouping_level_1      : tissue
  grouping_level_2      : compartment
  n_perms               : 100
  libraryType           : 10X
  run_analysis          : true

Max job request options
  max_memory            : 800 GB
  max_time              : 10d

Other parameters
  max_multiqc_email_size: 25 MB

------------------------------------------------------
 Only displaying parameters that differ from defaults.
------------------------------------------------------
Sep-11 21:18:27.492 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: PLOT, CLASS_INPUT_SS2, output_documentation, FIND_SPLIZ_SITES, CONVERT_PARQUET, PROCESS_CLASS_INPUT, ANN_SPLICES, CLASS_INPUT_10X, CALC_SPLIZVD, fastqc, PVAL_PERMUTATIONS, SUMMARIZE_RESULTS, get_software_versions, multiqc
Sep-11 21:18:27.586 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches label `process_medium` for process with name NFCORE_SPLIZ:SPLIZ_PIPELINE:SPLIZ:CALC_SPLIZVD
Sep-11 21:18:27.592 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Sep-11 21:18:27.592 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Sep-11 21:18:27.601 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Sep-11 21:18:27.612 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=32; memory=503.8 GB; capacity=32; pollInterval=100ms; dumpInterval=5m
Sep-11 21:18:27.763 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches label `process_medium` for process with name NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:PVAL_PERMUTATIONS
Sep-11 21:18:27.766 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Sep-11 21:18:27.767 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Sep-11 21:18:27.780 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches label `process_medium` for process with name NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:FIND_SPLIZ_SITES
Sep-11 21:18:27.782 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Sep-11 21:18:27.783 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Sep-11 21:18:27.790 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_low` matches label `process_low` for process with name NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:SUMMARIZE_RESULTS
Sep-11 21:18:27.792 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Sep-11 21:18:27.792 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Sep-11 21:18:27.802 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:process_medium` matches label `process_medium` for process with name NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:PLOT
Sep-11 21:18:27.813 [main] DEBUG nextflow.Session - Session aborted -- Cause: A process input channel evaluates to null -- Invalid declaration `path domain`
Sep-11 21:18:27.851 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] map
  [operator] reduce
  [operator] map

Sep-11 21:18:27.911 [main] WARN  nextflow.Nextflow - Found unexpected parameters:
* --outdir: ./results/test
* --numGenes: null
* --domain: null
Sep-11 21:18:27.916 [main] INFO  nextflow.Nextflow - - Ignore this warning: params.schema_ignore_params = "outdir,numGenes,domain" 
Sep-11 21:18:27.926 [main] ERROR nextflow.cli.Launcher - A process input channel evaluates to null -- Invalid declaration `path domain`
java.lang.IllegalArgumentException: A process input channel evaluates to null -- Invalid declaration `path domain`
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.script.params.BaseInParam.checkFromNotNull(BaseInParam.groovy:170)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.script.params.BaseInParam.setFrom(BaseInParam.groovy:181)
	at nextflow.script.ProcessDef.run(ProcessDef.groovy:175)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:95)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at Script_b1ebe85a$_runScript_closure1$_closure2.doCall(Script_b1ebe85a:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:95)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
	at Script_1a9f4c93$_runScript_closure1$_closure2.doCall(Script_1a9f4c93:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:95)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at Script_613c6d34$_runScript_closure11$_closure27.doCall(Script_613c6d34:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:95)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at Script_613c6d34$_runScript_closure12$_closure28.doCall(Script_613c6d34:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:186)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:170)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:52)
	at nextflow.script.ChainableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:191)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

**Comment by kaitlinchaung** [comment]
Closing because this was resolved by the latest push, which removed the offending domain variable
